# Stage 1: Build environment
FROM node:21-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Highly optimized production server using Nginx
FROM nginx:alpine
# Clear out default configurations
RUN rm /etc/nginx/conf.d/default.conf
# Copy our custom reverse proxy setup
COPY nginx.conf /etc/nginx/conf.d/
# Copy the compiled static web files from the builder stage straight into the Nginx public folder
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
