# Stage 1: Build environment
FROM node:21-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Highly optimized production server using Nginx
FROM nginx:alpine
# Copy the compiled static web files from the builder stage straight into the Nginx public folder
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

# Overwrite default Nginx configuration execution to keep it running smoothly in the foreground
CMD ["nginx", "-g", "daemon off;"]
